version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  commit-message:
    # Prefix all commit messages with "npm"
    prefix: "auto dependabot"

- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  commit-message:
    # Prefix all commit messages with "npm"
    prefix: "auto dependabot"
  groups:
    eslint:
      patterns:
        - "*eslint*"