
name: Build and test all the Kiota packages
on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            node-version: [18.x, 20.x]
        steps:
        - uses: actions/checkout@v4
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v4
          with:
            node-version: ${{ matrix.node-version }}
        - run: npm ci
        - run: npm run build
        - run: npm run test:coverage # Add junit/html to post coverage results

    # The check-build-matrix returns success if all matrix jobs in build are successful; otherwise, it returns a failure.
    # Use this as a PR status check for GitHub Policy Service instead of individual matrix entry checks.
    check-build-matrix:
      runs-on: ubuntu-latest
      needs: build
      if: always()
      steps:
        - name: All build matrix options are successful
          if: ${{ !(contains(needs.*.result, 'failure')) }}
          run: exit 0
        - name: One or more build matrix options failed
          if: ${{ contains(needs.*.result, 'failure') }}
          run: exit 1

    publish-npm:
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && github.event.before == 'release-please--branches--main--components--msgraph-ts-core-sdk')}}
        needs: build
        environment:
          name: production_feed
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - uses: actions/setup-node@v4
            with:
              node-version: 20
              registry-url: https://registry.npmjs.org/
          - run: |
              git config --global user.name '${GITHUB_ACTOR}'
              git config --global user.email '${GITHUB_ACTOR}@users.noreply.github.com'
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                GITHUB_ACTOR: ${{ secrets.GIT_USERNAME }}
          - run: npm ci
          - run: npm run build
          - run: npm publish --access public
            env:
              NODE_AUTH_TOKEN: ${{secrets.npm_token}}


